spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AYAU0K6BV/LtdDEPLLlJgRtCLRQvdkV67quBZlJvwwnXLx7IDIi1eUZsTnddgI3oiQEGuyLt/4h0GlE9WEIE0OXXwzxxfiA6JW66rXhytU86e0WNwsGycFtiVAxd+Q1dB2ED4vfVs9Iq9nN2zF6F2QzQAkme4uvTuLjMEu4DVXFevPz0q+D6nfGpbCs1citrQXQcqsZ9SzL8OnA+hQdL3W+W2KwTnKKnfs5z4Jv6P/GYy7p1sRlP/TDnlQ31RK5nEqPixSWGDvMiOoyJbezrbyRJEnBEpQiiR21UAs52Uc8DjrfcLUZpVIKRyXVaz3OxoZOVh8eRGDA4dmKuS0kEQPtEYCB6MLT4IGnpt1daVqqsUxES7BJQ3XHlMkze+LYApxorfA1pvGRH0hY+q+ZYH95pYoBhKK3iVQcKvSd3Fui2kHTTXY+V3kH3mxYT/LAJWGMPyyBpLj2ZHf5FaQWnlzZ60ypg/9dZHagcNqJe23RVacGJa0zqbUI1NtSVwHVHgZhZt9IE+RKNxgqWKGzZscLn6+dmyj6xFvEwswbTeIUsBg=='

token:
  expiration_time: 86400000
  secret: '{cipher}AYBYneJUg8SmXGRTgdasQpQqY8kvnyDROFWWuEu0PhLJq4MiS8rcViKFDkXkalDLqXDbuDERnkfzHOIUhhTdN6xPvj3nCb0QXOUCMIwPvzHtALEq+ZykehcTw7Y0FHtNSIAVR1+zTL+MPNXsKHd3aw56TEBesIX/lmEj7udwZ+Agu3KlaiNMq3HY1W/oUjHuNXiHV49IoYmOl/XritI9wNTuKzpd8ybLuiu16umbX00jNEMJix8eR7Z6QqEkLdG5vgB9DTS4IUpzmij0SAXvgJtppUnYfdc8woOtpfsAgGBb7J7vZMJp9wuM6FQBNZP5ZRkvlRN+R0Oawv8w0uQ4dWGlU+mt5u0gVsg69aY6IdwiZPqt5enM9BCgfgFQSmOk+mVjqM2wkRShK0z5ukNLtnirHcFZgnh10qreu4YDcODkz/FxsrhuYQlqGXqgjh/rBKUSGPu8m89TGrRZAKUNai6kvp4tMjt52u94n11y74o1Yf3Vp4hvJE1diF1whaZ1oFkeaed+dpDFoZPMOzXGVWigZe2XHr/lrWBbsa273Yi2G7tHCQkc3zXcNNRcPF88Euv4iuhChbzUUrBn+PVuOqKs'

gateway:
  ip: 192.168.45.36