spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

token:
  expiration_time: 86400000
  secret: user_token_doodoo_default

gateway:
  ip: 192.168.45.36